### ISSUE TITLE
Crash issue in Nexus 6

### ISSUE THREAD

**Issue by rameshkec85** [Ziggeo/Android-Client-SDK#10]
USER_COMMENT=null
STACK_TRACE=java.lang.IllegalArgumentException: Unsupported angle: 450
at android.media.MediaRecorder.setOrientationHint(MediaRecorder.java:493)
at com.ziggeo.androidsdk.recording.MediaRecorderManager.startRecording(MediaRecorderManager.java:134)
at com.ziggeo.androidsdk.ui.fragments.VideoRecorderFragment.startRecording(VideoRecorderFragment.java:348)
at com.ziggeo.androidsdk.ui.fragments.VideoRecorderFragment.record(VideoRecorderFragment.java:388)
at com.ziggeo.androidsdk.ui.fragments.VideoRecorderFragment.onClick(VideoRecorderFragment.java:177)
at android.view.View.performClick(View.java:5204)

**Comment by 3akat** [comment]
Hi @rameshkec85,
Thanks for reporting this. Can you please also tell how to reproduce this?

**Comment by rameshkec85** [comment]
Hi,
Thanks for the quick reply. I just ran the app and start recording app crashing with the above error.

**Comment by 3akat** [comment]
Thanks for info. 
Unfortunately I cant reproduce crash on my real nexus 5 or emulator nexus 6, so can't do fix right now. Will try to find the reason asap.

**Comment by 3akat** [comment]
Hi @rameshkec85,
I've got Nexus 6, still can't reproduce the issue. Can you please add more specific details? Test on other devices or somth?

**Comment by 3akat** [comment]
Closed due to inactivity.
