### ISSUE TITLE
Unable to record video with front camera

### ISSUE THREAD

**Issue by rameshkec85** [Ziggeo/Android-Client-SDK#14]
I have taken latest sdk and sample but i am getting below error in MOTOZPlay device.

https://github.com/Ziggeo/Android-Client-SDK/tree/d6ca2a0a30cfc13b1f6bb67fef17f691a46d4cf3

```
FATAL EXCEPTION: main
                                                                            Process: com.ziggeo.androidsdk.demo, PID: 26614
                                                                            java.lang.RuntimeException: start failed.
                                                                                at android.media.MediaRecorder.start(Native Method)
                                                                                at com.ziggeo.androidsdk.widgets.cameraview.Camera1.startRecording(Camera1.java:123)
                                                                                at com.ziggeo.androidsdk.widgets.cameraview.CameraView.startRecording(CameraView.java:435)
                                                                                at com.ziggeo.androidsdk.demo.CameraViewActivity.onClick(CameraViewActivity.java:138)
                                                                                at android.view.View.performClick(View.java:5612)
                                                                                at android.view.View$PerformClick.run(View.java:22288)
                                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**Comment by 3akat** [comment]
Hi @rameshkec85,
Unfortunately I can't reproduce the issue. Can you please provide more info?
1. Before crash log there is log from MediaRecorder with error code value, will look like 
`start failed: -_number_`
2. Also please put this code in `onCameraOpened` callback 
https://gist.github.com/3akat/a0e0c74f550c579079ef2b550c490c53
and share logs from it, will look like
```
04-10 09:52:43.813 22962-22962/? E/CameraViewActivity: Camera:0
04-10 09:52:43.813 22962-22962/? E/CameraViewActivity: Hardware level is:_number_
04-10 09:52:43.814 22962-22962/? E/CameraViewActivity: Camera:1
04-10 09:52:43.814 22962-22962/? E/CameraViewActivity: Hardware level is:_number_
```

That would be very helpful,
Thank you

**Comment by rameshkec85** [comment]
Thanks for the reply. FYI, My device is running on 7.0+

```
4-10 15:24:24.648 8281-8281/com.ziggeo.androidsdk.demo D/CameraViewActivity: onCameraClosed
04-10 15:24:24.864 8281-8281/com.ziggeo.androidsdk.demo D/CameraViewActivity: onCameraOpened
04-10 15:24:31.609 8281-8281/com.ziggeo.androidsdk.demo D/CameraViewActivity: onCameraClosed
04-10 15:24:31.698 8281-8281/com.ziggeo.androidsdk.demo D/CameraViewActivity: onCameraOpened
04-10 15:24:31.812 8281-8281/com.ziggeo.androidsdk.demo E/CameraViewActivity: Camera:0
04-10 15:24:31.812 8281-8281/com.ziggeo.androidsdk.demo E/CameraViewActivity: Hardware level is:2
04-10 15:24:31.818 8281-8281/com.ziggeo.androidsdk.demo E/CameraViewActivity: Camera:1
04-10 15:24:31.818 8281-8281/com.ziggeo.androidsdk.demo E/CameraViewActivity: Hardware level is:2
04-10 15:24:37.916 8281-8281/com.ziggeo.androidsdk.demo E/CameraViewActivity: Camera:0
04-10 15:24:37.916 8281-8281/com.ziggeo.androidsdk.demo E/CameraViewActivity: Hardware level is:2
04-10 15:24:37.926 8281-8281/com.ziggeo.androidsdk.demo E/CameraViewActivity: Camera:1
04-10 15:24:37.926 8281-8281/com.ziggeo.androidsdk.demo E/CameraViewActivity: Hardware level is:2
04-10 15:24:41.793 8281-8281/com.ziggeo.androidsdk.demo E/MediaRecorder: start failed: -19
04-10 15:24:41.793 8281-8281/com.ziggeo.androidsdk.demo D/AndroidRuntime: Shutting down VM
                                                                          
                                                                          
                                                                          --------- beginning of crash
04-10 15:24:41.800 8281-8281/com.ziggeo.androidsdk.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.ziggeo.androidsdk.demo, PID: 8281
                                                                          java.lang.RuntimeException: start failed.
                                                                              at android.media.MediaRecorder.start(Native Method)
                                                                              at com.ziggeo.androidsdk.widgets.cameraview.Camera1.startRecording(Camera1.java:123)
                                                                              at com.ziggeo.androidsdk.widgets.cameraview.CameraView.startRecording(CameraView.java:435)
                                                                              at com.ziggeo.androidsdk.demo.CameraViewActivity.onClick(CameraViewActivity.java:141)
                                                                              at android.view.View.performClick(View.java:5612)
                                                                              at android.view.View$PerformClick.run(View.java:22288)
                                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

```

**Comment by rameshkec85** [comment]
Hi @3akat,  any update on this ?

**Comment by 3akat** [comment]
Hi @rameshkec85, thank you for info but still no results for now, trying to find the reason.
If it is not hard, can you please try to run recording with default recorder? 
I mean `FullscreenRecorderActivity` or manually through `ziggeo.createVideo(...)`

**Comment by rameshkec85** [comment]
Hi @3akat , I have tested with front camera using both activities, which is working fine.
**FullscreenRecorderActivity** and **EmbeddedRecorderActivity** 


But it is failed with **CameraViewActivity.java**

**Comment by 3akat** [comment]
@rameshkec85 great, thanks for info, I will get rid of the difference in implementation today

**Comment by 3akat** [comment]
Hi @rameshkec85, please, checkout the new version.

**Comment by rameshkec85** [comment]
Thanks @3akat , its working now.
