### ISSUE TITLE
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?

### ISSUE THREAD

**Issue by objectorientedperson** [Ziggeo/Android-Client-SDK#15]
at android.app.ContextImpl.startActivity(ContextImpl.java:672)
                                                                                at android.app.ContextImpl.startActivity(ContextImpl.java:659)
                                                                                at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
                                                                                at com.ziggeo.androidsdk.Ziggeo.startRecorder(Ziggeo.java:465)
                                                                                at com.ziggeo.androidsdk.demo.FullscreenRecorderActivity.onCreate(FullscreenRecorderActivity.java:66)

**Comment by 3akat** [comment]
Hi @objectorientedperson, thanks for reporting! Will check this soon.

**Comment by 3akat** [comment]
@objectorientedperson Can you also tell steps to reproduce?

**Comment by objectorientedperson** [comment]
@3akat I just cloned the project to studio and run. It crashes at this line:

mZiggeo.startRecorder();

in FullscreenRecorderActivity

**Comment by objectorientedperson** [comment]
@3akat anything new?

**Comment by 3akat** [comment]
Hi @objectorientedperson, the fix will be published today

**Comment by 3akat** [comment]
@objectorientedperson please, check out the new version.
