### ISSUE TITLE
TextureView background attribute crashes 7.0 and above.

### ISSUE THREAD

**Issue by objectorientedperson** [Ziggeo/Android-Client-SDK#16]
Hello, SDK causes crash for devices 7.0 and above. Here is the stacktrace.

android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.ziggeo.androidsdk.widgets.cameraview.CameraView
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                   Caused by: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.ziggeo.androidsdk.widgets.cameraview.CameraView
                   Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.ziggeo.androidsdk.widgets.cameraview.CameraView
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Constructor.newInstance0(Native Method)
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                      at com.myregistry.refactor.core.BaseMRActivity.onCreate(BaseMRActivity.java:46)
                      at android.app.Activity.performCreate(Activity.java:6679)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                   Caused by: android.view.InflateException: Binary XML file line #15: Binary XML file line #15: Error inflating class android.view.TextureView
                   Caused by: android.view.InflateException: Binary XML file line #15: Error inflating class android.view.TextureView
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Constructor.newInstance0(Native Method)
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:700)
                      at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:68)
                      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)
E/AndroidRuntime:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                      at android.view.View.inflate(View.java:21010)
                      at com.ziggeo.androidsdk.widgets.cameraview.TextureViewPreview.<init>(TextureViewPreview.java:38)
                      at com.ziggeo.androidsdk.widgets.cameraview.CameraView.createPreviewImpl(CameraView.java:168)
                      at com.ziggeo.androidsdk.widgets.cameraview.CameraView.<init>(CameraView.java:130)
                      at com.ziggeo.androidsdk.widgets.cameraview.CameraView.<init>(CameraView.java:118)
                      at java.lang.reflect.Constructor.newInstance0(Native Method)
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                      at com.myregistry.refactor.core.BaseMRActivity.onCreate(BaseMRActivity.java:46)
                      at android.app.Activity.performCreate(Activity.java:6679)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                   Caused by: java.lang.UnsupportedOperationException: TextureView doesn't support displaying a background drawable
                      at android.view.TextureView.setBackgroundDrawable(TextureView.java:316)
                      at android.view.View.setBackground(View.java:18247)
                      at android.view.View.<init>(View.java:4600)
                      at android.view.View.<init>(View.java:4109)
                      at android.view.View.<init>(View.java:4088)
                      at android.view.TextureView.<init>(TextureView.java:146)
                      	... 42 more

**Comment by 3akat** [comment]
Hi @objectorientedperson, thanks for reporting.
I can't reproduce the issue, so a few questions
1. What device model do you use?
2. Is the crash occurs with default demo configuration, or did you do some specific config?

**Comment by objectorientedperson** [comment]
@3akat Hello,

1. I've tested with Samsung s3 mini (Android 4), LG Optimus Zone 3 (Android 5), LG Nexus 5 (Android 6) and all worked fine. Only in Motorola Nexus 6 (Android 7) it crashes.

2. I have not used any specific config, added your demo config by using: 
compile "com.github.ZiggeoJitpackService:Android-SDK:0.71.7"

**Comment by 3akat** [comment]
@objectorientedperson it looks like an issue with android themes or support components.
Do you have the same issue in demo from the repository?

**Comment by 3akat** [comment]
@objectorientedperson any news?

**Comment by 3akat** [comment]
Closing due to inactivity.
@objectorientedperson please, reopen if the issue still exists.
