### ISSUE TITLE
Null Pointer exception on URLEncodedUtils

### ISSUE THREAD

**Issue by jiahaoliuliu** [Ziggeo/Android-Client-SDK#4]
Hi:
I am using Ziggeo in a simple app and when I am uploading the video to the server I am receiving the follow null pointer exception. This happens on Embedded video recorder.

```
11-05 14:31:58.308 E/AndroidRuntime(12023): FATAL EXCEPTION: main
11-05 14:31:58.308 E/AndroidRuntime(12023): Process: com.jiahaoliuliu.simpleziggeointegration, PID: 12023
11-05 14:31:58.308 E/AndroidRuntime(12023): java.lang.NullPointerException
11-05 14:31:58.308 E/AndroidRuntime(12023): 	at cz.msebera.android.httpclient.client.utils.URLEncodedUtils.format(URLEncodedUtils.java:341)
11-05 14:31:58.308 E/AndroidRuntime(12023): 	at cz.msebera.android.httpclient.client.utils.URLEncodedUtils.format(URLEncodedUtils.java:322)
11-05 14:31:58.308 E/AndroidRuntime(12023): 	at com.ziggeo.androidsdk.services.ZiggeoService.onIntentProcessed(ZiggeoService.java:418)
11-05 14:31:58.308 E/AndroidRuntime(12023): 	at com.ziggeo.androidsdk.services.ZiggeoService$1.run(ZiggeoService.java:392)
11-05 14:31:58.308 E/AndroidRuntime(12023): 	at android.os.Handler.handleCallback(Handler.java:733)
11-05 14:31:58.308 E/AndroidRuntime(12023): 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-05 14:31:58.308 E/AndroidRuntime(12023): 	at android.os.Looper.loop(Looper.java:136)
11-05 14:31:58.308 E/AndroidRuntime(12023): 	at android.app.ActivityThread.main(ActivityThread.java:5072)
11-05 14:31:58.308 E/AndroidRuntime(12023): 	at java.lang.reflect.Method.invokeNative(Native Method)
11-05 14:31:58.308 E/AndroidRuntime(12023): 	at java.lang.reflect.Method.invoke(Method.java:515)
11-05 14:31:58.308 E/AndroidRuntime(12023): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
11-05 14:31:58.308 E/AndroidRuntime(12023): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
11-05 14:31:58.308 E/AndroidRuntime(12023): 	at dalvik.system.NativeStart.main(Native Method)
```

I am not doing anything special. The source code could be found here:
https://github.com/jiahaoliuliu/SimpleZiggeoIntegration

**Comment by 3akat** [comment]
Hi @jiahaoliuliu,
I can't repeat it on my SGS4 mini and nexus 4, can you please tell me your device name and android version?

**Comment by jiahaoliuliu** [comment]
@3akat I am using XiaoMi Mi3

**Comment by 3akat** [comment]
@jiahaoliuliu 
fixed

**Comment by jiahaoliuliu** [comment]
@3akat Thanks!
